# global_costmap:
#   global_frame: map
#   robot_base_frame: base_link
#   update_frequency: 5.0
#   static_map: false

global_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  width: 15
  height: 15
  origin_x: -7.5
  origin_y: -7.5
  static_map: true
  rolling_window: true
  inflation_radius: 0.25
  resolution: 0.1